name: Run tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      RPC_USER: satoshi
      RPC_PASSWORD: amiens
      RPC_URL: 127.0.0.1
      RPC_PORT: 44555
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v2
    - name: Install Node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Npm Install
      run: npm install
    - name: Run Standard
      run: npm run lint
    - name: Run tests
      run: |
        mkdir data
        npm test